### ISSUE TITLE
Huawei Notification Message Click ，OnEvent callback

### ISSUE THREAD

**Issue by donald99** [weixinjie/RePush#1]
Huawei hms，Notification Message Click，onEvent method no callback，why ？

**Comment by donald99** [comment]
"hps"->"ext"->"customize"下的内容为用户自定义扩展信息，必须带上customize，才可以点击消息通知栏有回调OnEvent。

见文档扩展消息处
华为文档地址：http://developer.huawei.com/consumer/cn/service/hms/catalog/huaweipush.html?page=hmssdk_huaweipush_devguide_s

 "ext" : {                                        
             "biTag" : "Trump",                                        
             "customize" :[{"season":"Spring"},{"weather":"raining"}]                            
       }

**Comment by donald99** [comment]
服务端推送消息payload样例如下：
payload={"hps":{"msg":{"action":{"param":{"appPkgName":"com.push.demo"},"type":3},"type":3,"body":{"title":"message title","content":"message content"}},"ext":{"biTag":"Trump","customize":[{"messageid":"1234567890","description":"this is message description.","title":"this is Message title."}]}}}

**Comment by weixinjie** [comment]
OnEvent函数在App后台运行的情况下服务端发送推送的时候带上ext后会调用，但是在App完全被杀死的时候,虽然能收到推送,但是点击推送消息onEvent函数是不会被触发的(如果你的设备开了自启动权限则仍然会被调用)。
正确的做法是(经过咨询华为推送的设计者):
1.使用华为推送服务的自定义动作来推送
2.注册一个Activity来接收隐式并且做转发。这块代码里面有体现

**Comment by weixinjie** [comment]
onEvent在App完全被杀死的情况下不会被触发的原因是在App被完全杀死的时候,华为系统会从系统级别拦截该App的广播。所以onEvent是不会被触发的。

**Comment by donald99** [comment]
服务端能在华为渠道获取到设备在线状态吗？比如：App完全被杀死

**Comment by weixinjie** [comment]
我理解的你的意思是想你们的服务端根据用户的设备在线情况只给在线的用户推消息吧？
1.目前我们没有发现服务端获取设备在线状态的api
2.服务端调用openpush.message.api.send接口推送的异步消息会有缓存功能
3.华为的推送服务默认缓存离线消息24个小时
4.经过我们的测试,华为推送的离线缓存功能并不是那么的稳定

**Comment by donald99** [comment]
使用华为推送服务的自定义动作来推送，这个自定义动作，在控制台可以完美解决

但是自己开发发送后台对接华为服务，应该如何自定义？有相关demo吗？
